Error: Adding new project cards via BuddyForms (posts in group)
Logged in as Camille (full Admin rights). Tried to create a brand new project card/blog post. Action yielded the following error: 
"You do not have the required user role to use this form."

@svenl77